/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../pages/__root'
import { Route as PublicRouteRouteImport } from './../pages/_public/route'
import { Route as AuthRouteRouteImport } from './../pages/_auth/route'
import { Route as PublicFinalizarCadastroIndexRouteImport } from './../pages/_public/finalizar-cadastro/index'
import { Route as PublicCadastrarIndexRouteImport } from './../pages/_public/cadastrar/index'
import { Route as PublicentrarIndexRouteImport } from './../pages/_public/(entrar)/index'
import { Route as AuthTradesIndexRouteImport } from './../pages/_auth/trades/index'
import { Route as AuthPerfilIndexRouteImport } from './../pages/_auth/perfil/index'
import { Route as AuthHomeIndexRouteImport } from './../pages/_auth/home/index'
import { Route as AuthColecaoIndexRouteImport } from './../pages/_auth/colecao/index'
import { Route as AuthAlbumIndexRouteImport } from './../pages/_auth/album/index'
import { Route as AuthColecaoAdicionarIndexRouteImport } from './../pages/_auth/colecao/Adicionar/index'
import { Route as AuthAlbumPaisIndexRouteImport } from './../pages/_auth/album/$pais/index'
import { Route as AuthAlbumColarStickerIdIndexRouteImport } from './../pages/_auth/album/colar/$stickerId/index'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicFinalizarCadastroIndexRoute =
  PublicFinalizarCadastroIndexRouteImport.update({
    id: '/finalizar-cadastro/',
    path: '/finalizar-cadastro/',
    getParentRoute: () => PublicRouteRoute,
  } as any)
const PublicCadastrarIndexRoute = PublicCadastrarIndexRouteImport.update({
  id: '/cadastrar/',
  path: '/cadastrar/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicentrarIndexRoute = PublicentrarIndexRouteImport.update({
  id: '/(entrar)/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthTradesIndexRoute = AuthTradesIndexRouteImport.update({
  id: '/trades/',
  path: '/trades/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPerfilIndexRoute = AuthPerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthHomeIndexRoute = AuthHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthColecaoIndexRoute = AuthColecaoIndexRouteImport.update({
  id: '/colecao/',
  path: '/colecao/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAlbumIndexRoute = AuthAlbumIndexRouteImport.update({
  id: '/album/',
  path: '/album/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthColecaoAdicionarIndexRoute =
  AuthColecaoAdicionarIndexRouteImport.update({
    id: '/colecao/Adicionar/',
    path: '/colecao/Adicionar/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAlbumPaisIndexRoute = AuthAlbumPaisIndexRouteImport.update({
  id: '/album/$pais/',
  path: '/album/$pais/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAlbumColarStickerIdIndexRoute =
  AuthAlbumColarStickerIdIndexRouteImport.update({
    id: '/album/colar/$stickerId/',
    path: '/album/colar/$stickerId/',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicentrarIndexRoute
  '/album/': typeof AuthAlbumIndexRoute
  '/colecao/': typeof AuthColecaoIndexRoute
  '/home/': typeof AuthHomeIndexRoute
  '/perfil/': typeof AuthPerfilIndexRoute
  '/trades/': typeof AuthTradesIndexRoute
  '/cadastrar/': typeof PublicCadastrarIndexRoute
  '/finalizar-cadastro/': typeof PublicFinalizarCadastroIndexRoute
  '/album/$pais/': typeof AuthAlbumPaisIndexRoute
  '/colecao/Adicionar/': typeof AuthColecaoAdicionarIndexRoute
  '/album/colar/$stickerId/': typeof AuthAlbumColarStickerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicentrarIndexRoute
  '/album': typeof AuthAlbumIndexRoute
  '/colecao': typeof AuthColecaoIndexRoute
  '/home': typeof AuthHomeIndexRoute
  '/perfil': typeof AuthPerfilIndexRoute
  '/trades': typeof AuthTradesIndexRoute
  '/cadastrar': typeof PublicCadastrarIndexRoute
  '/finalizar-cadastro': typeof PublicFinalizarCadastroIndexRoute
  '/album/$pais': typeof AuthAlbumPaisIndexRoute
  '/colecao/Adicionar': typeof AuthColecaoAdicionarIndexRoute
  '/album/colar/$stickerId': typeof AuthAlbumColarStickerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_auth/album/': typeof AuthAlbumIndexRoute
  '/_auth/colecao/': typeof AuthColecaoIndexRoute
  '/_auth/home/': typeof AuthHomeIndexRoute
  '/_auth/perfil/': typeof AuthPerfilIndexRoute
  '/_auth/trades/': typeof AuthTradesIndexRoute
  '/_public/(entrar)/': typeof PublicentrarIndexRoute
  '/_public/cadastrar/': typeof PublicCadastrarIndexRoute
  '/_public/finalizar-cadastro/': typeof PublicFinalizarCadastroIndexRoute
  '/_auth/album/$pais/': typeof AuthAlbumPaisIndexRoute
  '/_auth/colecao/Adicionar/': typeof AuthColecaoAdicionarIndexRoute
  '/_auth/album/colar/$stickerId/': typeof AuthAlbumColarStickerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album/'
    | '/colecao/'
    | '/home/'
    | '/perfil/'
    | '/trades/'
    | '/cadastrar/'
    | '/finalizar-cadastro/'
    | '/album/$pais/'
    | '/colecao/Adicionar/'
    | '/album/colar/$stickerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/album'
    | '/colecao'
    | '/home'
    | '/perfil'
    | '/trades'
    | '/cadastrar'
    | '/finalizar-cadastro'
    | '/album/$pais'
    | '/colecao/Adicionar'
    | '/album/colar/$stickerId'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_auth/album/'
    | '/_auth/colecao/'
    | '/_auth/home/'
    | '/_auth/perfil/'
    | '/_auth/trades/'
    | '/_public/(entrar)/'
    | '/_public/cadastrar/'
    | '/_public/finalizar-cadastro/'
    | '/_auth/album/$pais/'
    | '/_auth/colecao/Adicionar/'
    | '/_auth/album/colar/$stickerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/finalizar-cadastro/': {
      id: '/_public/finalizar-cadastro/'
      path: '/finalizar-cadastro'
      fullPath: '/finalizar-cadastro/'
      preLoaderRoute: typeof PublicFinalizarCadastroIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/cadastrar/': {
      id: '/_public/cadastrar/'
      path: '/cadastrar'
      fullPath: '/cadastrar/'
      preLoaderRoute: typeof PublicCadastrarIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/(entrar)/': {
      id: '/_public/(entrar)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicentrarIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/trades/': {
      id: '/_auth/trades/'
      path: '/trades'
      fullPath: '/trades/'
      preLoaderRoute: typeof AuthTradesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/perfil/': {
      id: '/_auth/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof AuthPerfilIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/home/': {
      id: '/_auth/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof AuthHomeIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/colecao/': {
      id: '/_auth/colecao/'
      path: '/colecao'
      fullPath: '/colecao/'
      preLoaderRoute: typeof AuthColecaoIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/album/': {
      id: '/_auth/album/'
      path: '/album'
      fullPath: '/album/'
      preLoaderRoute: typeof AuthAlbumIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/colecao/Adicionar/': {
      id: '/_auth/colecao/Adicionar/'
      path: '/colecao/Adicionar'
      fullPath: '/colecao/Adicionar/'
      preLoaderRoute: typeof AuthColecaoAdicionarIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/album/$pais/': {
      id: '/_auth/album/$pais/'
      path: '/album/$pais'
      fullPath: '/album/$pais/'
      preLoaderRoute: typeof AuthAlbumPaisIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/album/colar/$stickerId/': {
      id: '/_auth/album/colar/$stickerId/'
      path: '/album/colar/$stickerId'
      fullPath: '/album/colar/$stickerId/'
      preLoaderRoute: typeof AuthAlbumColarStickerIdIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAlbumIndexRoute: typeof AuthAlbumIndexRoute
  AuthColecaoIndexRoute: typeof AuthColecaoIndexRoute
  AuthHomeIndexRoute: typeof AuthHomeIndexRoute
  AuthPerfilIndexRoute: typeof AuthPerfilIndexRoute
  AuthTradesIndexRoute: typeof AuthTradesIndexRoute
  AuthAlbumPaisIndexRoute: typeof AuthAlbumPaisIndexRoute
  AuthColecaoAdicionarIndexRoute: typeof AuthColecaoAdicionarIndexRoute
  AuthAlbumColarStickerIdIndexRoute: typeof AuthAlbumColarStickerIdIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAlbumIndexRoute: AuthAlbumIndexRoute,
  AuthColecaoIndexRoute: AuthColecaoIndexRoute,
  AuthHomeIndexRoute: AuthHomeIndexRoute,
  AuthPerfilIndexRoute: AuthPerfilIndexRoute,
  AuthTradesIndexRoute: AuthTradesIndexRoute,
  AuthAlbumPaisIndexRoute: AuthAlbumPaisIndexRoute,
  AuthColecaoAdicionarIndexRoute: AuthColecaoAdicionarIndexRoute,
  AuthAlbumColarStickerIdIndexRoute: AuthAlbumColarStickerIdIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicentrarIndexRoute: typeof PublicentrarIndexRoute
  PublicCadastrarIndexRoute: typeof PublicCadastrarIndexRoute
  PublicFinalizarCadastroIndexRoute: typeof PublicFinalizarCadastroIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicentrarIndexRoute: PublicentrarIndexRoute,
  PublicCadastrarIndexRoute: PublicCadastrarIndexRoute,
  PublicFinalizarCadastroIndexRoute: PublicFinalizarCadastroIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
